<a href="https://colab.research.google.com/github/gunavathibaskaran170/AI-project-/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **OneEncoding**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df= pd.read_csv('/content/drive/MyDrive/DATASET /preprocessing_dataset.csv')
df.head()

      Name   Age Gender   Salary Department
0    Alice  25.0      F  50000.0         HR
1      Bob  30.0      M  60000.0    Finance
2  Charlie   NaN      M  55000.0         IT
3    David  40.0      M  58000.0         HR
4      Eve  22.0      F  52000.0         IT

In [ ]:
from sklearn.impute import SimpleImputer
im=SimpleImputer(strategy='most_frequent')
imp1=SimpleImputer(strategy='median')
df[['Age','Salary']]=imp1.fit_transform(df[['Age','Salary']])
df[['Gender']]=im.fit_transform(df[['Gender']])

In [ ]:
from sklearn.preprocessing import LabelEncoder
lc=LabelEncoder()
df['Gender_encoder']=lc.fit_transform(df[['Gender']])
df

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

      Name    Age Gender   Salary Department  Gender_encoder
0    Alice   25.0      F  50000.0         HR               0
1      Bob   30.0      M  60000.0    Finance               1
2  Charlie   29.0      M  55000.0         IT               1
3    David   40.0      M  58000.0         HR               1
4      Eve   22.0      F  52000.0         IT               0
5    Frank   35.0      M  61000.0    Finance               1
6    Grace  120.0      F  59000.0    Finance               0
7    Henry   28.0      M  59000.0         HR               1
8      Ivy   29.0      F  63000.0         IT               0
9     Jack   27.0      M  62000.0    Finance               1

In [ ]:
d2= pd.read_csv('/content/drive/MyDrive/DATASET /preprocessing_dataset.csv')
from sklearn.impute import SimpleImputer
im=SimpleImputer(strategy='most_frequent')
imp1=SimpleImputer(strategy='median')
d2[['Age','Salary']]=imp1.fit_transform(d2[['Age','Salary']])
d2[['Gender']]=im.fit_transform(d2[['Gender']])

from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder(sparse_output=False)
d2['Gender']=oh.fit_transform(d2[['Gender']])
d2

      Name    Age  Gender   Salary Department
0    Alice   25.0     1.0  50000.0         HR
1      Bob   30.0     0.0  60000.0    Finance
2  Charlie   29.0     0.0  55000.0         IT
3    David   40.0     0.0  58000.0         HR
4      Eve   22.0     1.0  52000.0         IT
5    Frank   35.0     0.0  61000.0    Finance
6    Grace  120.0     1.0  59000.0    Finance
7    Henry   28.0     0.0  59000.0         HR
8      Ivy   29.0     1.0  63000.0         IT
9     Jack   27.0     0.0  62000.0    Finance

In [ ]:
d3= pd.read_csv('/content/drive/MyDrive/DATASET /preprocessing_dataset.csv')
from sklearn.impute import SimpleImputer
im=SimpleImputer(strategy='most_frequent')
imp1=SimpleImputer(strategy='median')
d3[['Age','Salary']]=imp1.fit_transform(d3[['Age','Salary']])
d3[['Gender']]=im.fit_transform(d3[['Gender']])

d3=pd.get_dummies(d3,columns=['Gender'],drop_first=True)# drop  first is used to remove the column heading
d3
#if you want int type
#d3=pd.get_dummies(d3,columns=['Gender'], drop_first=True, dtype=int)

      Name    Age   Salary Department  Gender_M
0    Alice   25.0  50000.0         HR     False
1      Bob   30.0  60000.0    Finance      True
2  Charlie   29.0  55000.0         IT      True
3    David   40.0  58000.0         HR      True
4      Eve   22.0  52000.0         IT     False
5    Frank   35.0  61000.0    Finance      True
6    Grace  120.0  59000.0    Finance     False
7    Henry   28.0  59000.0         HR      True
8      Ivy   29.0  63000.0         IT     False
9     Jack   27.0  62000.0    Finance      True